--- # mount playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: mount the remote data partition
    mount: name=/mnt/data  src=/dev/xvda1 fstype=ext3 opts=rw state=present
