--- # acl playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Get ACL information on the /etc/ansible.acl.txt remote file
    acl: name=/etc/ansible.acl.txt entity=ansible etype=user permissions="rw" state=present
    register: aclinfo
  - debug: msg={{ aclinfo }}
