--- # delegateto playbook example
- hosts: centos
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Run a remote ping on the centos server
    command: ping -c 4 172.31.20.201
    delegate_to: 127.0.0.1
  - name: Install a package
    yum: pkg=lynx state=latest

