--- # Jinj2template playbook example
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: yes
  vars:
    username: ansible
    password: linuxacadmey
    connectionType: SFTP
  tasks:
  - name: Install the configuration file customized for the system
    template: src=test.conf.j2 dest=/home/ansible/ansible.conf owner=ansible group=ansible mode=750
