--- # command playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Check for python packages
    command: /home/ansible/test.sh
    args:
      chdir: /home/ansible/testing
