--- # apache2module playbook example
- hosts: ubuntu
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Add the alias module in apache2
    apache2_module: name=alias state=present
  - name: Disable the alias module in apache2
    apache2_module: name=alias state=absent
