--- # yum playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install Apache webserver
    action: yum name=httpd state=installed
  - name: Install Lynx web browser
    yum: name=lynx state=latest
  - name: Remove lynx web browser
    action: yum name=lynx state=absent
  - name: Equivalent of yum upgrade
    action: yum name=* state=latest
