--- # seboolean playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
  - name: Change Boolean for anonymous writes on the web server
    seboolean: name=httpd_anon_write state=yes persistent=yes
