--- # unarchive playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: copy and unarchive a file
    unarchive: src=test.tar.gz dest=/home/ansible/unarchive
