--- # fetch playbook example
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Copy remote hosts file to control server
    fetch: src=/etc/hosts dest=/home/ansible/prefix-{{ ansible_hostname }} flat=yes
