--- # htpasswd playbook example
- hosts: ubuntu
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install the python dependencies
    apt: pkg=python-passlib state=latest
  - name: Adding a user to web site authentication
    htpasswd: path=/etc/apache2/.htpasswd name=ansible1 password=123456 owner=ansible1 group=ansible1 mode=0640
