--- # Lookup playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - debug: msg="Lookup hero name wayne {{ lookup('csvfile', 'Wayne file=lookup.csv delimiter=, default=NOMATCH')}} from csv file present in current directory"
  - debug: msg="{{ lookup('env', 'HOME')}} is the value set in centos machine environment variables"
