--- # script playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Run system_uptime.sh file on remote centos machine
    script: system_uptime.sh creates=/home/ansible/system_uptime.log 
