--- # MariaDb Server Playbook
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  pre_tasks:
  - name: When did the database server role start
    raw: date > /home/ansible/startofdbrole.txt
  roles:
  - mariadbserver
  post_tasks:
  - name: when did the databse server role end
    raw: date > /home/ansible/endofdbrole.txt

