--- # group playbook example
- hosts: centos
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Add a new group called newgroup
    group: name=newgroup state=present
