--- # copy playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Copy test1 file from files directory to remote user home directory
    action: copy src=files/test1.txt dest=/home/ansible/test1.txt mode=0655 owner=ansible group=ansible
  - name: Copy test2 file from files directory to remote user home directory with backup
    action: copy src=files/test2.txt dest=/home/ansible/test2.txt mode=0655 owner=ansible group=ansible backup=yes
