--- # selinux playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Change SELinux Configuration to Permissive
    selinux: policy=targeted state=permissive
