--- # selinux playbook example
- hosts: centos
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Change SELinux Configuration to Permissive
    selinux: policy=targeted state=permissive
