--- # Playbook for redhat web servers
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  pre_tasks:
  - name: When did the role start
    raw: date > /home/ansible/startofrole.log
  roles:
  - { role: redhat_webservers, when: "ansible_os_family == 'RedHat'" }
  post_tasks: 
  - name: When did the role end
    raw: date > /home/ansible/endofrole.log 
