--- # Ec2 VPC network facts module example
- hosts: local
  connection: ssh
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
  - awscreds.yml
  tasks:
  - name: Get information about vpcs
    ec2_vpc_net_facts:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
    register: vpc_net_facts
  - name: Print VPC network facts
    debug: var=vpc_net_facts
