--- # Ec2 snapshot module example
- hosts: local
  connection: local
  become: yes
  become_method: sudo
  gather_facts: no
  remote_user: ec2-user
  vars_files:
  - awscreds.yml
  tasks:
  - name: Take a snapshot of the running instance root volume
    ec2_snapshot: 
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      snapshot_id: snap-09b6bf90bb058632f
      state: absent
      wait: no
    register: snapshot
