--- # Ec2 volume module example
- hosts: local
  connection: ssh
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
  - awscreds.yml
  tasks:
  - name: Create a new volume and attach to running instance
    ec2_vol:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance: i-06c4e0ab72eaf62f4
      volume_size: 1
      device_name: sde
    register: volume_result
