--- # service playbook example
- hosts: centos
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install web server
    action: yum name=httpd state=installed
  - name: Start the web server
    service: name=httpd state=started
  - name: Enable httpd after restart
    service: name=httpd enabled=yes
  - name: Stop the web server
    service: name=httpd state=stopped
