--- # loops playbook example
- hosts: centos
  remote_user: ansible
  connection: ssh
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: Add list of users using loop
    user: name={{ item }} state=present
    with_items:
    - user1
    - user2
    - user3
