--- # NFS Client Playbook
- hosts: local
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  pre_tasks:
  - name: When did the nfs client role start
    raw: date > /home/ansible/startofclientrole.txt
  roles:
  - client
  post_tasks:
  - name: when did the nfs client role end
    raw: date > /home/ansible/endofclientrole.txt
