--- # notify playbook example
- hosts: centos
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install apache web server
    action: yum name=httpd state=installed 
    notify: Start Httpd
  handlers:
  - name: Start Httpd
    action: service name=httpd state=started

