--- # mail playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Send an email to test user indicating build completion
    mail:
      host='localhost'
      port=25
      to="ansible"
      subject="Our host is finished deploying"
      body="System called {{ ansible_hostname }} has been successfully setup"
