--- # Include1 playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  vars_files:
  - variables/variables.yml
  tasks:
  - include: packages/packages.yml
  - include: commands/commands.yml
  - name: Install telnet client
    yum: pkg=httpd state=latest
  handlers:
  - include: handlers/handlers.yml 
