--- # Error handling playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Execute a command that will fail
    command: /bin/false
    ignore_errors: yes
  - name: Install telnet client
    yum: name=telnet state=latest
