--- # waitfor playbook example
- hosts: centos
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Installing the apache tomcat
    action: yum name=tomcat state=installed
  - name: Waiting for port 8080 to listen
    wait_for:
      port: 8080
      state: started
  - name: Verifying the lynx installation
    action: yum name=lynx state=present
