--- # Pause playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install httpd
    action: yum name=httpd state=installed
  - name: Pausing
    pause:
      prompt: "Make Sure the installation is complete..."
  - name: Verify lynx installation
    action: yum name=lynx state=present
    
