- name: Install the NFS server utilities, services and libraries
  yum: pkg={{ item }} state=latest
  with_items:
  - "{{ nfsutils_pkg }}"
  - "{{ nfslibs_pkg }}"
- name: Copy the Export file to remote server
  copy: src=exports.template dest=/etc/exports owner=root group=root mode=644
  notify:
  - Start Server Services
