--- # shell playbook example
- hosts: centos
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Executing a remote command - uptime
    shell: /usr/bin/uptime >> uptime.log
    args:
      chdir: logs/
      creates: uptime.log

