--- # shell playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Executing a remote command - uptime
    shell: /usr/bin/uptime >> uptime.log
    args:
      chdir: logs/
      creates: uptime.log

