--- # kernel blacklist playbook example
- hosts: centos
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Blacklist the DUMMY kernel module
    kernel_blacklist: name=dummy state=present
