--- # kernel blacklist playbook example
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Blacklist the DUMMY kernel module
    kernel_blacklist: name=dummy state=present
