--- # When playbook example
- hosts: all
  remote_user: ansible
  connection: ssh
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    playbook_type: conditionalexample
  tasks:
  - name: Install Apache Appropriate to the distribution type(Debian/Ubuntu)
    command: apt-get -y install apache2
    when: ansible_os_family == "Debian"
  - name: Install Apache Appropriate to the distribution type(redhat/Centos)
    command: yum install -y httpd
    when: ansible_os_family == "RedHat"
