- name: Copy the Export file to remote server
  copy: src=exports.template dest=/etc/exports owner=root group=root mode=644
  notify:
  - Install Client Packages
  - Create Client Mount
  - Client Mount Server Resource
